=== wingerjc/ChanteySongs/source/initial_xml/texts/chantey.dtd
<!ELEMENT chantey (title,collection,location,author,perfomer?,use?,ID,crossref?,text?,abc?)>
<!ELEMENT title (CDATA) >
<!ELEMENT collection (CDATA) >
<!ELEMENT location (CDATA) >
<!ELEMENT author (personid+) >
<!ELEMENT performer (personid) >
<!ELEMENT use (usetype+) >
<!ELEMENT ID (CDATA) >
<!ELEMENT crossref (ID+) >
<!ELEMENT text (CDATA) >
<!ELEMENT abc (CDATA) >
<!ELEMENT personid (CDATA) >
<!ELEMENT usetype (CDATA) >

=== wingerjc/ChanteySongs/source/initial_xml/texts/R000934_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>The Dreadnaught</title>
    <collection>1894BMORCOM</collection>
    <location>21</location>
    <author>
        <personid>Trad</personid>
    </author>
    <ID>R000924</ID>

<text>
There's a saucy wild packet, and a packet of fame,
She belongs to New York, and the Dreadnaught's her name.
She is bound to the westward where strong winds do blow,
Bound away in the Dreadnaught, to the westward we go.

The time of her sailing is now drawing nigh;
Farewell pretty May, I must bid you goodbye,
Farewell to old Englang and all there we hold dear,
Bound away in the Dreadnaught, to the westward we'll steer.

Oh, the hauling out of Waterloo dock,
Where the boys and the girls on the pier head do flock;
They will give us three cheers whil ther tears freely flow,
Saying, god bless the Dreadnaught whereso'er she may go.

Oh! the Dreadnaught is waiting in the Mersey so free,
Waiting for the Independence to tow her to sea;
For to round the black rock where the Mersey does flow,
Bound away in the Dreadnaught, to the westward we'll go.

Oh! the Dreadnaught's a'howling down the wild Irish shore,
Captain Samuels commands her as he's oft done before,
While the sailors like lions walk the decks to and fro,
Bound away in the Dreadnaught, to the westward we'll go.

Oh! the Dreadnaught's a'sailing the Atlantic so wide,
Where the dark, heavy seas roll along the black side
With the sails neatly spread, and the red cross to show,
Bound away in the Dreadnaught, to the westward we'll go.

Oh! the Dreadnaught's becalmed on the banks of Newfoundland,
Where the water's so green and the bottom is sand,
Where the fish of the ocean swim round to and fro,
Bound away in the Dreadnaught, to the westward we'll go.

Oh! the Dreadnaught's arrived in America once more,
We'll go ashor shipmates on the land we adore,
See our wives and our sweethearts, be merry and free;
Drink a health to the Dreadnaught whereso'er she may be.

Here's a health to the Dreadnaughtand to all her brave crew,
Here's a health to Capt. Samuels and officers too,
Talk about your flash packets, "Swallow Tail" and "Black Ball,"
But the Dreadnaught's the clipper to beat one and all.
</text>

</chantey>

=== wingerjc/ChanteySongs/source/initial_xml/texts/R000319_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>On the Banks of Sacramento</title>
    <collection>1894BMORCOM</collection>
    <location>61</location>
    <author>
        <personid>Trad</personid>
    </author>
    <ID>R000319</ID>

<text>
As I was walking down the street,
    Hoodah, to my Hoodah;
A charming girl I chanced to meet,
    Hoodah, Hoodah day.

Blow ye wind heigho,
    For California, O;
There's plenty of gold
    So I've been told
On the banks of Sacramento.
</text>

</chantey>

=== wingerjc/ChanteySongs/source/initial_xml/texts/W000001_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>Hail Columbia</title>
    <collection>1883BNAVWMA</collection>
    <location>7</location>
    <author>
        <personid>None</personid>
    </author>
    <ID>W000001</ID>

<text>
Hail! Columbia, happy land! Hail! ye heroes, heav'n-born band,
Who fought and bled in freedom's cause, Who fought and bled in freedom's cause,
And when the storm of war was gone, Enjoyed the peace your valor won;
Let independence be your boast, Ever mindful what it cost,
Ever gratefule for the prize, Let its altar reach the skies.

Chorus
Firm, united, let us be, Rallying round our liberty;
As a band of brothers joined, Peace and safety we shall find.

Immortal patriots, rise once more! Defend your rights, defend your shore;
Let no rude foe with impious hand, Let no rude foe with impious hand
Invade the shrine where sacred lies Of toil and blood the well earned prize;
While offering peace sincere and just, In heav'n we place a manly trust,
That truth and justice may prevail, ev'ry scheme of bondage fail.

Sound, sound the trump of fame!  

</text>

<abc>
X:
T:
C:
M: 4/4
L: 1/8
K:
|]
</abc>

</chantey>

=== wingerjc/ChanteySongs/source/initial_xml/texts/R003282_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>Reuben Ranzo</title>
    <collection>1883BNAVWMA</collection>
    <location>4</location>
    <author>
        <personid>Trad</personid>
    </author>
    <use>
        <usetype>long haul</usetype>
    </use>
    <ID>R003282</ID>

<text>
Oh, poor Reuben Ranzo, _Ranzo,_ boys, _Ranzo!_
    Oh, poor Reuben Ranzo, _Ranzo,_ boys, _Ranzo!_

Oh, Reuben was no sailor, _Ranzo,_ boys, _Ranzo!_
    Oh, Reuben was no sailor, _Ranzo,_ boys, _Ranzo!_

He shipped on board of a whaler, _Ranzo,_ boys, _Ranzo!_
    He shipped on board of a whaler, _Ranzo,_ boys, _Ranzo!_

The captain was a bad man, _Ranzo,_ boys, _Ranzo!_
    The captain was a bad man, _Ranzo,_ boys, _Ranzo!_

He put him in the rigging, _Ranzo,_ boys, _Ranzo!_
    He put him in the rigging, _Ranzo,_ boys, _Ranzo!_

He gave him six and thirty, _Ranzo,_ boys, _Ranzo!_
    He gave him six and thirty, _Ranzo,_ boys, _Ranzo!_

Oh I poor Reuben Ranzo, _Ranzo,_ boys, _Ranzo!_
    Oh Ipoor Reuben Ranzo, _Ranzo,_ boys, _Ranzo!_
</text>

<abc>
X: 3282
T: Reuben Ranzo
C: Trad.
M: 4/4
L: 1/4
K: F
A c B A| G2 A2|G G G2| A (G2 C) |F2 F D| F2 C2|F A A2| G F2 z|]
w: Oh, poor Reu-ben Ran-zo, Ran-zo, boys, Ran-zo! Oh, poor Reu-ben Ran-zo, Ran-zo, boys, Ran-zo
</abc>

</chantey>

=== wingerjc/ChanteySongs/source/initial_xml/texts/R000324_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>Shanadore</title>
    <collection>1883BNAVWMA</collection>
    <location>5</location>
    <author>
        <personid>Trad</personid>
    </author>
    <use>
        <usetype>long haul</usetype>
    </use>
    <ID>R000324</ID>

<text>
Shanadore's a rolling river, _Hurrah!_ you rolling river,
    Oh, Shanadore's a rolling river, _Ah Hah!_ I'm bound away, O'er the wild Missouri.

Shanadore's a packet sailor,
    Chorus.

Shanadore's a bright mulatto,
    Chorus.

Shanadore, I long to hear you,
    Chorus
</text>

<abc>
X: 324
T: Shanadore
C: Trad.
M: 3/4
L: 1/8
K: C
C C | C3 D E F | G E2 z2 c | A3 G A G | E G2 z2 G | A A A3 E |
w: Shan-a-dore's a roll-ing riv-er, Hur-rah! you roll-ing riv-er, Oh, Shan-a-dore's a
G E D C z E | E3 C E F | G3 z C D | (E E3) D | D C3 |]
w: roll-ing riv-er, Ah Hah! I'm bound a-way, O'er the wild_ Mis-sou-ri.
</abc>

</chantey>

=== wingerjc/ChanteySongs/source/initial_xml/texts/R000809_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>Haul Away Joe</title>
    <collection>1883BNAVWMA</collection>
    <location>4</location>
    <author>
        <personid>Trad</personid>
    </author>
    <use>
        <usetype>short haul</usetype>
    </use>
    <ID>R000809</ID>

<text>
Way, haul away; O, haul away my Rosey. Way, haul away; O, haul away _Joe._
</text>

<abc>
X: 809
T: Haul Away Joe
C: Trad.
M: 4/4
L: 1/8
K: Eb
B2 B3/2 A/ F3 D|E E E E FG AF|B2 B3/2 A/ F3 D|E E F2 B,4|]
w: Way, haul a-way; O, haul a-way my ro--sey._ Way, haul a-way; O, haul a-way Joe.
</abc>

</chantey>

=== wingerjc/ChanteySongs/source/initial_xml/texts/R000485_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>John Francois</title>
    <collection>1883BNAVWMA</collection>
    <location>5</location>
    <author>
        <personid>Trad</personid>
    </author>
    <use>
        <usetype>long haul</usetype>
    </use>
    <ID>R000485</ID>

<text>
Oh, Boney was a warrior, _Away,_ hey way!
    Oh, Boney was a warrior, _John Francois._
% it is noted that Francois is pronounced "Franswar"

Oh, Boney went to Roo-shy,
    Chorus.

Oh, Boney went to Proo-shy,
    Chorus.

He crossed the Rock Mountains,
    Chorus.

He made a mistake at Waterloo,
    Chorus.

He died at Saint Helena,
    Chorus.
</text>

<abc>
X: 485
T: John Francois
C: Trad.
M: 6/8
L: 1/8
K: C
CD | E2 D E2 D | C3 C2 E | G3 A3 | HF3 z E |
w: Oh,_ Bo-ney was a warri-or, A-way, hey way! Oh,
D2 D D2 C| B,3 A3 | G3 G3 | (E3 E) ]
w:  Bo-ney was a warri-or, John Fran-cois.
</abc>

</chantey>
