=== wingerjc/ChanteySongs/source/texts/chantey.dtd
<!ELEMENT chantey (title,collection?,author,perfomer?,use?,ID,crossref?,text?,abc?)>
<!ELEMENT title (CDATA) >
<!ELEMENT collection (CDATA) >
<!ELEMENT author (personid+) >
<!ELEMENT performer (personid) >
<!ELEMENT use (usetype+) >
<!ELEMENT ID (CDATA) >
<!ELEMENT crossref (ID+) >
<!ELEMENT text (CDATA) >
<!ELEMENT abc (CDATA) >
<!ELEMENT personid (CDATA) >
<!ELEMENT usetype (CDATA) >

=== wingerjc/ChanteySongs/source/texts/R000208_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>Paddy, Come Work On the Railway</title>
    <collection>1883BNAVWMA</collection>
    <location>6</location>
    <author>
        <personid>Trad</personid>
    </author>
    <use>
        <usetype>capstan</usetype>
    </use>
    <ID>R000208</ID>

<text>
In eighteen hundred and sixty three, I came across the stormy sea, My
dung'ree breeches I put on, To work upon the railway, the railway, To
work upon the railway, Oh, poor Paddy, come work on the railway.
</text>

<abc>
X: 208
T: Paddy, Come Work On the Railway
C: Trad.
M: 6/8
L: 1/8
K: C
C | E2 E E D C | E2 F G2 E | C2 C F2 E | D2 B, G,2 G/F/ |
w: In eight-een hun-dred and sixt-y three, I came a-cross the storm-y sea, My_
E2 E ED C | E2 F G2 F | E2 C D2 B, |  (C2 E) D2 C | (B,2 A,) G,2 G, |
w: dung'-ree breech--es I put on, To work up-on the rail--way, the rail--way, To
C2 D E2 F | (G2 A) (HGC) HG/ F/ | E D C D C B, | C3 C2 z |]
w: work up-on the rail--way,_ Oh, poor Pad-dy, come work on the rail-way.
</abc>

</chantey>

=== wingerjc/ChanteySongs/source/texts/R002624_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>Knock a Man Down</title>
    <collection>1883BNAVWMA</collection>
    <location>6</location>
    <author>
        <personid>Trad</personid>
    </author>
    <use>
        <usetype>long haul</usetype>
    </use>
    <ID>R002624</ID>

<text>
I wish I was in Mobile bay,
    _Way, hey,_ knock a man down,
A rolling  cotton night and day,
    _This_ is the time to knock a man down.

I wish I was in New Orleans,
    Chorus.
Where Jackson Gave the British beans,
    Chorus.

I wish I was at Boston city,
    Chorus.
a walking with my lovely Kitty,
    Chorus.

I wish I was in New York Town,
    Chorus.
a walking Broadway up and down,
    Chorus.

I wish I was in Liverpool,
    Chorus.
a going to a Yankee school,
    Chorus.
</text>

<abc>
X: 2624
T: Knock a Man Down
C: Trad.
M: 3/8
L: 1/8
K: C
E | G2 E | G2 E | G2 E | HC2 z | G3 | A3 | F >E F | D2 E|
w: I wish I was in Mo-bile bay, Way, hey, knock a man down, A
F2 F | F2 E | D2 A | A2 z | G G G | G2 F | E >D E | C2 z |]
w: roll-ing  cot-ton night and day, This is the time to knock a man down.
</abc>

</chantey>

=== wingerjc/ChanteySongs/source/texts/R000703_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>Blow, My Bully Boys, Blow.</title>
    <collection>1883BNAVWMA</collection>
    <author>
        <personid>Trad</personid>
    </author>
    <use>
        <usetype>long haul</usetype>
    </use>
    <ID>R000703</ID>

<text>
Oh, Sally Brown's a bright mulatto; _Blow,_ boys, _blow!_
    Oh she drinks rum and chews tobacco, _Blow,_ my bully boys, _blow!_

Oh, Sally Brown, I long to see you; _Blow,_ boys, _blow!_
    Chorus, etc.

Oh, Sally Brown, I'll ne'e deceiv you, _Blow,_ boys, _blow!_
    Chorus, etc.
</text>

<abc>
X: 703
T: Blow, My Bully Boys, Blow
C: Trad.
M: 4/4
L: 1/8
K: C
CD| E3 C E3 C | E2 E2 D C2 z | D4 E4 | F6 A2 |
w: Oh,_ Sal-ly Brown's a bright mu-lat-to; Blow, boys, blow! Oh,
G3 E F3 D | C2 D2 E F3 | E2 G2 DD E2 | HC6 |]
w: she drinks rum and chews to-bac-co, Blow, my bul-ly boys, blow!
</abc>

</chantey>

=== wingerjc/ChanteySongs/source/texts/R000317_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>Rio Grande</title>
    <collection>1883BNAVMWA</collection>
    <location>6</location>
    <author>
        <personid>Trad</personid>
    </author>
    <use>
        <usetype>capstan</usetype>
    </use>
    <ID>R000317</ID>

<text>
I'm bound away this very day, Oh, you Rio!
    I'm bound away this very day, I'm bound for the Rio Grande.
And away you Rio! Oh, you Rio,
    I'm bound away this very day, I'm bound for the Rio Grande.
</text>

<abc>
X: 317
T: Rio Grande
C: Trad.
M: 6/8
L: 1/8
K: C
CD | E2 E E2 D | C(D E) DC z | (G3 G2) E | A G2 z2 G | 
w: I'm_ bound a-way this ver--y day,_ Oh,_ you Ri-o! I'm
A2 A GF E | FG F ED C | E3/2 E/ E D2 G | C3 C C3/2 D/ | (E3 E2) C | D C2 z z2 |
w: bound a-way_ this ver--y day,_ I'm bound for the Ri-o Gran-de. And a-way_ you Ri-o!
(G3 G2) E | A G2 z2 G | A2 A GF E | FG F ED C | E E E D2 G | C3 C z2 |]
w: Oh,_ you Ri-o, I'm bound a-way_ this ver--y day,_ I'm bound for the Ri-o Gran-de.
</abc>

</chantey>

=== wingerjc/ChanteySongs/source/texts/R000651_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>Whiskey Johnny</title>
    <collection>1883BNAVWMA</collection>
    <location>5</location>
    <author>
        <personid>Trad</personid>
    </author>
    <use>
        <usetype>long haul</usetype>
    </use>
    <ID>R000651</ID>

<text>
Whiskey is the life of man.
    _Whiskey_ Johnny,
We'll drink our whiskey when we can:
    _Whiskey_ for my Johnny.

I drink whiskey, and my wife drinks gin,
    Chorus.
And the way she drinks it is a sin,
    Chorus.

I and my wife cannot agree,
    Chorus.
For she drinks whiskey in her tea,
    Chorus.

I had a girl her name was Lize,
    Chorus.
She put whiskey in her pies,
    Chorus.

Whiskey's gone and I'll go too,
    Chorus.
For without whiskey I can't do,
    Chorus.
</text>

<abc>
X: 651
T: Whiskey Johnny
C: Trad.
M: 4/4
L: 1/4
K: C
 C E E > D | D C C2 | C E2 z | C E2 G |
w: Whis-key is the life of man. Whis-key John-ny, We'll
 G E F E | D D G,2 | B, D F > E | E C2 z |]
w: drink our whis-key when we can: Whis-key for my John-ny.

</abc>

</chantey>

=== wingerjc/ChanteySongs/source/texts/R000652_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>Haul the Bowline</title>
    <collection>1883BNAVWMA</collection>
    <location>3</location>
    <author>
        <personid>Trad</personid>
    </author>
    <use>
        <usetype>short haul</usetype>
    </use>
    <ID>R000652</ID>

<text>
Haul the bowline, Kitty is my darling;
    Haul the bowline, the bowline, _haul!_

Haul the bowline, the clipper ship's a rolling;
    Haul the bowline, the bowline, _haul!_

Haul the bowline, our bully mate is growling;
    Haul the bowline, the bowline, _haul!_
</text>

<abc>
X: 652
T: Haul the Bowline
C: Trad.
M: 4/4
L: 1/8
K: G
G3 G F2 D2|E F G E DC B,2|G3 G F2 D D|E2 F2 G4|]
w: Haul the bow-line, Kit-ty is my Dar--ling; Haul the bow-line, the bow-line, haul! 
</abc>

</chantey>

=== wingerjc/ChanteySongs/source/texts/R000353_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>Johnny Boker</title>
    <collection>1883BNAVWMA</collection>
    <location>4</location>
    <author>
        <personid>Trad</personid>
    </author>
    <use>
        <usetype>short haul</usetype>
    </use>
    <ID>R000353</ID>

<text>
Oh! do, my Johnny Boker, come rock and roll me Over; Do, my Johnny Boker, _do._
</text>

<abc>
X: 353
T: Johnny Boker
C: Trad.
M: 2/4
L: 1/8
K: G
D|G G G G|G2 F G|A G F G|EF G2|D D D D|E2 F2|G2 z]
w: Oh! do, my John-ny Bo-ker, come rock and roll me O--ver; Do, my John-ny Bo-ker, do.
</abc>

</chantey>

=== wingerjc/ChanteySongs/source/texts/R000481_001.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="chantey.xsl"?>
<!DOCTYPE chantey SYSTEM "chantey.dtd">
<chantey>
    <title>My Tommy's Gone A High-Low.</title>
    <collection>1883BNAVWMA</collection>
    <author>
        <personid>Trad</personid>
    </author>
    <use>
        <usetype>long haul</usetype>
    </use>
    <ID>R000481</ID>
    <crossref>
        <ID>R000650</ID>
    </crossref>

<text>
My Tommy's gone and I'll go too, _Hurrah!_ you high-low; 
    For without Tommy I can't do, My _Tommy's_ gone a _high-low._

My Tommy's gone on the eastern shore,
    Chorus.

My Tommy's gone to Balimore,
    Chorus.
</text>

<abc>
X: 481
T: My Tommy's Gone A High-Low
C: Trad.
M: 3/4
L: 1/8
K: G
D D E | G3 B A E | (G4 G) B | (A4 A) G | B (A E3) A | 
w: My Tom-my's gone and I'll go too,_ Hur-rah!_ you high-low;_ For 
A A A3 F | G E D3 D | G G B3 G | A G2 |]
w: with-out Tom-my I can't do, My Tom-my's gone a high-low.
</abc>

</chantey>
